### ISSUE TITLE
Why choose action using a max policy in SARSA?

### ISSUE THREAD

**Issue by vaibkumr** [moskomule/pytorch.rl.learning#1]
https://github.com/moskomule/pytorch.rl.learning/blob/master/predl/table/sarsa.py#L17

According to Sutton and Barto's book the action `_action` is derived using some policy (e.g. epsilon-greedy) while you've simply used the max policy which is meant to be done in Q-learning.  
Please let me know if I am at wrong here.

**Comment by moskomule** [comment]
Hi, I did this long before when I tried to learn RL. It may be my misunderstanding at that time.

**Comment by vaibkumr** [comment]
Yes, I think it might be an error. Nevertheless, thank you for your work. 
I have made a pull request, only for sarsa now, with second action also derived from the policy because SARSA is an on-policy learning algorithm.

**Comment by moskomule** [comment]
Thank you, PR is very helpful. I'll check and merge it.
